version: '3'
services:
  minio:
    image: minio/minio:latest
    ports:
      - 9090:9000
    environment:
      - MINIO_ROOT_USER=dummy
      - MINIO_ROOT_PASSWORD=dummysecretkey
    entrypoint: sh
    command: -c "
      cp -r /export/* /data/;
      minio server /data;"
    volumes:
      - ./data:/data
      - ./export:/export
